// Hand-written support for the generated discriminated-union wrappers.
// Not regenerated by `npm run generate:dotnet`.
#nullable enable

namespace Microsoft.AgentHostProtocol;

/// <summary>
/// Base class for every generated discriminated-union wrapper (for example
/// <c>StateAction</c>, <c>ResponsePart</c>, <c>ToolCallState</c>). The active
/// variant is stored in <see cref="Value"/> as the concrete payload type;
/// unknown discriminator values (introduced by a newer protocol version) are
/// stored as a raw <see cref="System.Text.Json.JsonElement"/> so re-encoding
/// round-trips faithfully.
/// </summary>
public abstract class AhpUnion
{
    internal string? Discriminator { get; set; }

    /// <summary>
    /// The active variant value. Either one of the union's concrete payload
    /// types, a raw <see cref="System.Text.Json.JsonElement"/> for an unknown
    /// variant, or <see langword="null"/> when no variant is set.
    /// </summary>
    public object? Value { get; set; }

    /// <summary>Creates a union wrapper with no active variant.</summary>
    protected AhpUnion()
    {
    }

    /// <summary>Creates a union wrapper around the given variant value.</summary>
    /// <param name="value">The concrete variant payload.</param>
    protected AhpUnion(object? value)
    {
        Value = value;
    }
}
