// Hand-written generic converter shared by every generated discriminated
// union. Not regenerated by `npm run generate:dotnet`.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace Microsoft.AgentHostProtocol;

/// <summary>
/// System.Text.Json converter base for discriminated unions whose variant is
/// selected by a string-valued discriminator field. The generated code
/// supplies the discriminator field name and the wire-value → CLR-type map
/// via a tiny subclass; all of the read/write logic lives here.
/// </summary>
/// <typeparam name="T">The generated union wrapper type.</typeparam>
public abstract class UnionConverter<T> : JsonConverter<T>
    where T : AhpUnion, new()
{
    private readonly string _discriminator;
    private readonly IReadOnlyDictionary<string, Type> _variants;
    private readonly bool _allowUnknown;

    /// <summary>Creates a union converter.</summary>
    /// <param name="discriminator">The JSON field that selects the variant.</param>
    /// <param name="variants">Map from discriminator wire value to CLR payload type.</param>
    /// <param name="allowUnknown">
    /// When <see langword="true"/>, an unrecognized discriminator value is
    /// preserved as a raw <see cref="JsonElement"/> rather than throwing.
    /// </param>
    protected UnionConverter(
        string discriminator,
        IReadOnlyDictionary<string, Type> variants,
        bool allowUnknown)
    {
        _discriminator = discriminator;
        _variants = variants;
        _allowUnknown = allowUnknown;
    }

    /// <inheritdoc />
    public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        using JsonDocument doc = JsonDocument.ParseValue(ref reader);
        JsonElement root = doc.RootElement;

        string? disc = null;
        if (root.ValueKind == JsonValueKind.Object
            && root.TryGetProperty(_discriminator, out JsonElement discElement)
            && discElement.ValueKind == JsonValueKind.String)
        {
            disc = discElement.GetString();
        }

        var result = new T();
        if (disc is not null && _variants.TryGetValue(disc, out Type? variantType))
        {
            JsonTypeInfo typeInfo = options.GetTypeInfo(variantType);
            result.Value = JsonSerializer.Deserialize(root, typeInfo);
            result.Discriminator = disc;
        }
        else if (_allowUnknown)
        {
            // Preserve the original JSON verbatim for loss-free round-trips.
            result.Value = root.Clone();
        }
        else
        {
            throw new JsonException(
                $"Unknown {typeof(T).Name} discriminator '{disc}' (field '{_discriminator}')");
        }

        return result;
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        object? inner = value?.Value;
        if (inner is null)
        {
            writer.WriteNullValue();
            return;
        }

        if (inner is JsonElement raw)
        {
            // Unknown variant — emit the preserved JSON exactly as received.
            raw.WriteTo(writer);
            return;
        }

        JsonTypeInfo typeInfo = options.GetTypeInfo(inner.GetType());
        JsonElement serialized = JsonSerializer.SerializeToElement(inner, typeInfo);
        if (serialized.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException(
                $"{typeof(T).Name} variant '{inner.GetType().Name}' must serialize as an object");
        }

        string? wireValue = null;
        if (serialized.TryGetProperty(_discriminator, out JsonElement serializedDiscriminator)
            && serializedDiscriminator.ValueKind == JsonValueKind.String)
        {
            wireValue = serializedDiscriminator.GetString();
        }

        wireValue ??= value?.Discriminator;
        if (wireValue is not null
            && (!_variants.TryGetValue(wireValue, out Type? storedType)
                || storedType != inner.GetType()))
        {
            wireValue = null;
        }

        foreach (KeyValuePair<string, Type> variant in _variants)
        {
            if (wireValue is not null)
            {
                break;
            }

            if (variant.Value == inner.GetType())
            {
                wireValue = variant.Key;
                break;
            }
        }

        if (wireValue is null)
        {
            throw new JsonException(
                $"Unknown {typeof(T).Name} variant type '{inner.GetType().Name}'");
        }

        writer.WriteStartObject();
        writer.WriteString(_discriminator, wireValue);
        foreach (JsonProperty property in serialized.EnumerateObject())
        {
            if (property.NameEquals(_discriminator))
            {
                continue;
            }

            property.WriteTo(writer);
        }
        writer.WriteEndObject();
    }
}
