/**
 * Agent Host Protocol — Type Definitions
 *
 * @module agent-host-protocol
 * @description Canonical TypeScript type definitions for the Agent Host Protocol.
 * These types are the source of truth from which documentation and JSON Schema
 * are generated.
 */

// State types
export type {
  URI,
  StringOrMarkdown,
  RootState,
  RootConfigState,
  AgentInfo,
  ProtectedResourceMetadata,
  ProjectInfo,
  SessionModelInfo,
  ModelSelection,
  AgentSelection,
  SessionState,
  SessionSummary,
  ChatState,
  ChatSummary,
  ChatOrigin,
  ChangesSummary,
  SessionConfigState,
  Turn,
  ActiveTurn,
  Message,
  MessageOrigin,
  MessageAttachment,
  MessageAttachmentBase,
  TextPosition,
  TextRange,
  TextSelection,
  SimpleMessageAttachment,
  MessageEmbeddedResourceAttachment,
  MessageResourceAttachment,
  MessageAnnotationsAttachment,
  MarkdownResponsePart,
  ContentRef,
  ToolCallResponsePart,
  ReasoningResponsePart,
  SystemNotificationResponsePart,
  ResponsePart,
  ToolCallResult,
  ToolCallStreamingState,
  ToolCallPendingConfirmationState,
  ToolCallRunningState,
  ToolCallPendingResultConfirmationState,
  ToolCallCompletedState,
  ToolCallCancelledState,
  ToolCallState,
  ConfirmationOption,
  ToolDefinition,
  ToolAnnotations,
  ToolResultTextContent,
  ToolResultEmbeddedResourceContent,
  ToolResultResourceContent,
  ToolResultContent,
  FileEdit,
  ToolResultFileEditContent,
  ToolResultTerminalContent,
  ToolResultSubagentContent,
  SessionActiveClient,
  PendingMessage,
  ChatInputAnswer,
  ChatInputAnswerValue,
  ChatInputTextAnswerValue,
  ChatInputNumberAnswerValue,
  ChatInputBooleanAnswerValue,
  ChatInputSelectedAnswerValue,
  ChatInputSelectedManyAnswerValue,
  ChatInputAnswered,
  ChatInputSkipped,
  ChatInputOption,
  ChatInputQuestion,
  ChatInputTextQuestion,
  ChatInputNumberQuestion,
  ChatInputBooleanQuestion,
  ChatInputSingleSelectQuestion,
  ChatInputMultiSelectQuestion,
  ChatInputRequest,
  UsageInfo,
  ErrorInfo,
  Snapshot,
  TerminalInfo,
  TerminalClientClaim,
  TerminalSessionClaim,
  TerminalClaim,
  TerminalState,
  TerminalContentPart,
  TerminalUnclassifiedPart,
  TerminalCommandPart,
  Changeset,
  ChangesetState,
  ChangesetFile,
  ChangesetOperation,
  AnnotationsSummary,
  AnnotationsState,
  Annotation,
  AnnotationEntry,
  TelemetryCapabilities,
  ResourceWatchState,
  ResourceChange,
} from './state.js';

export {
  PolicyState,
  SessionLifecycle,
  SessionStatus,
  ChatOriginKind,
  TurnState,
  MessageKind,
  MessageAttachmentKind,
  ResponsePartKind,
  ToolCallStatus,
  ToolCallConfirmationReason,
  ToolCallCancellationReason,
  ConfirmationOptionKind,
  ToolResultContentType,
  PendingMessageKind,
  ChatInputAnswerState,
  ChatInputAnswerValueKind,
  ChatInputQuestionKind,
  ChatInputResponseKind,
  TerminalClaimKind,
  ChangesetStatus,
  ChangesetOperationStatus,
  ChangesetOperationScope,
  ResourceChangeType,
} from './state.js';

// Action types
export type {
  ActionEnvelope,
  ActionOrigin,
  RootAgentsChangedAction,
  RootActiveSessionsChangedAction,
  SessionReadyAction,
  SessionCreationFailedAction,
  SessionChatAddedAction,
  SessionChatRemovedAction,
  SessionChatUpdatedAction,
  SessionDefaultChatChangedAction,
  ChatTurnStartedAction,
  ChatDeltaAction,
  ChatResponsePartAction,
  ChatToolCallStartAction,
  ChatToolCallDeltaAction,
  ChatToolCallReadyAction,
  ChatToolCallApprovedAction,
  ChatToolCallDeniedAction,
  ChatToolCallConfirmedAction,
  ChatToolCallCompleteAction,
  ChatToolCallResultConfirmedAction,
  ChatToolCallContentChangedAction,
  ChatTurnCompleteAction,
  ChatTurnCancelledAction,
  ChatErrorAction,
  SessionTitleChangedAction,
  ChatUsageAction,
  ChatReasoningAction,
  SessionModelChangedAction,
  SessionAgentChangedAction,
  SessionServerToolsChangedAction,
  SessionActiveClientSetAction,
  SessionActiveClientRemovedAction,
  ChatPendingMessageSetAction,
  ChatPendingMessageRemovedAction,
  ChatQueuedMessagesReorderedAction,
  ChatInputAnswerChangedAction,
  ChatInputCompletedAction,
  ChatInputRequestedAction,
  ChatTruncatedAction,
  SessionIsReadChangedAction,
  SessionIsArchivedChangedAction,
  SessionActivityChangedAction,
  SessionConfigChangedAction,
  ChangesetStatusChangedAction,
  ChangesetFileSetAction,
  ChangesetFileRemovedAction,
  ChangesetContentChangedAction,
  ChangesetOperationsChangedAction,
  ChangesetOperationStatusChangedAction,
  ChangesetClearedAction,
  AnnotationsSetAction,
  AnnotationsRemovedAction,
  AnnotationsEntrySetAction,
  AnnotationsEntryRemovedAction,
  StateAction,
  RootTerminalsChangedAction,
  RootConfigChangedAction,
  TerminalDataAction,
  TerminalInputAction,
  TerminalResizedAction,
  TerminalClaimedAction,
  TerminalTitleChangedAction,
  TerminalCwdChangedAction,
  TerminalExitedAction,
  TerminalClearedAction,
  TerminalCommandExecutedAction,
  TerminalCommandFinishedAction,
  TerminalCommandDetectionAvailableAction,
  ResourceWatchChangedAction,
} from './actions.js';

export { ActionType } from './actions.js';

// Generated action origin types
export type {
  RootAction,
  SessionAction,
  ClientSessionAction,
  ServerSessionAction,
  ChatAction,
  ClientChatAction,
  ServerChatAction,
  TerminalAction,
  ClientTerminalAction,
  ServerTerminalAction,
  ChangesetAction,
  ClientChangesetAction,
  ServerChangesetAction,
  AnnotationsAction,
  ClientAnnotationsAction,
  ServerAnnotationsAction,
  ResourceWatchAction,
  ClientResourceWatchAction,
  ServerResourceWatchAction,
} from './action-origin.generated.js';

export { IS_CLIENT_DISPATCHABLE } from './action-origin.generated.js';

// Reducer functions
export {
  rootReducer,
  sessionReducer,
  chatReducer,
  terminalReducer,
  changesetReducer,
  annotationsReducer,
  resourceWatchReducer,
  isClientDispatchable,
} from './reducers.js';

// Command types
export type {
  InitializeParams,
  InitializeResult,
  ClientCapabilities,
  PingParams,
  ReconnectParams,
  ReconnectReplayResult,
  ReconnectSnapshotResult,
  ReconnectResult,
  SubscribeParams,
  SubscribeResult,
  CreateSessionParams,
  SessionForkSource,
  DisposeSessionParams,
  CreateChatParams,
  ChatForkSource,
  DisposeChatParams,
  CreateTerminalParams,
  DisposeTerminalParams,
  ListSessionsParams,
  ListSessionsResult,
  ResourceReadParams,
  ResourceReadResult,
  ResourceWriteParams,
  ResourceWriteResult,
  ResourceListParams,
  DirectoryEntry,
  ResourceListResult,
  ResourceCopyParams,
  ResourceCopyResult,
  ResourceDeleteParams,
  ResourceDeleteResult,
  ResourceMoveParams,
  ResourceMoveResult,
  ResourceResolveParams,
  ResourceResolveResult,
  ResourceMkdirParams,
  ResourceMkdirResult,
  ResourceRequestParams,
  ResourceRequestResult,
  CreateResourceWatchParams,
  CreateResourceWatchResult,
  FetchTurnsParams,
  FetchTurnsResult,
  UnsubscribeParams,
  DispatchActionParams,
  AuthenticateParams,
  AuthenticateResult,
  ResolveSessionConfigParams,
  ResolveSessionConfigResult,
  ConfigPropertySchema,
  ConfigSchema,
  SessionConfigPropertySchema,
  SessionConfigSchema,
  SessionConfigCompletionsParams,
  SessionConfigCompletionsResult,
  SessionConfigValueItem,
  CompletionsParams,
  CompletionsResult,
  CompletionItem,
  InvokeChangesetOperationParams,
  InvokeChangesetOperationResult,
  ChangesetOperationTarget,
  ChangesetOperationFollowUp,
} from './commands.js';

export { ReconnectResultType, ContentEncoding, CompletionItemKind, ResourceType, ResourceWriteMode } from './commands.js';

// Notification types
export type {
  SessionAddedParams,
  SessionRemovedParams,
  SessionSummaryChangedParams,
  ProgressParams,
  AuthRequiredParams,
  OtlpExportLogsParams,
  OtlpExportTracesParams,
  OtlpExportMetricsParams,
} from './notifications.js';

export { AuthRequiredReason } from './notifications.js';

// Message types (JSON-RPC wire format)
export type {
  JsonRpcRequest,
  JsonRpcSuccessResponse,
  JsonRpcErrorResponse,
  JsonRpcResponse,
  JsonRpcNotification,
  AhpErrorResponse,
  CommandMap,
  ServerCommandMap,
  ClientNotificationMap,
  ServerNotificationMap,
  AhpRequest,
  AhpServerRequest,
  AhpSuccessResponse,
  AhpServerSuccessResponse,
  AhpResponse,
  AhpServerResponse,
  AhpNotification,
  AhpClientNotification,
  AhpServerNotification,
  ProtocolMessage,
} from './messages.js';

// Error codes
export {
  JsonRpcErrorCodes,
  AhpErrorCodes,
} from './errors.js';
export type {
  AhpErrorCode,
  JsonRpcErrorCode,
  AhpError,
  AhpErrorCodeWithData,
  AhpErrorDetailsMap,
  AuthRequiredErrorData,
  PermissionDeniedErrorData,
} from './errors.js';

// Version registry
export {
  PROTOCOL_VERSION,
  SUPPORTED_PROTOCOL_VERSIONS,
  ACTION_INTRODUCED_IN,
  NOTIFICATION_INTRODUCED_IN,
  isActionKnownToVersion,
  isNotificationKnownToVersion,
  compareProtocolVersions,
} from './version/registry.js';
