/**
 * Agent Host Protocol — Type Definitions
 *
 * @module agent-host-protocol
 * @description Canonical TypeScript type definitions for the Agent Host Protocol.
 * These types are the source of truth from which documentation and JSON Schema
 * are generated.
 */

// State types
export type {
  URI,
  StringOrMarkdown,
  RootState,
  RootConfigState,
  AgentInfo,
  ProtectedResourceMetadata,
  ProjectInfo,
  SessionModelInfo,
  ModelSelection,
  SessionState,
  SessionSummary,
  SessionConfigState,
  Turn,
  ActiveTurn,
  UserMessage,
  MessageAttachment,
  MessageAttachmentBase,
  TextPosition,
  TextRange,
  TextSelection,
  SimpleMessageAttachment,
  MessageEmbeddedResourceAttachment,
  MessageResourceAttachment,
  MarkdownResponsePart,
  ContentRef,
  ToolCallResponsePart,
  ReasoningResponsePart,
  SystemNotificationResponsePart,
  ResponsePart,
  ToolCallResult,
  ToolCallStreamingState,
  ToolCallPendingConfirmationState,
  ToolCallRunningState,
  ToolCallPendingResultConfirmationState,
  ToolCallCompletedState,
  ToolCallCancelledState,
  ToolCallState,
  ConfirmationOption,
  ToolDefinition,
  ToolAnnotations,
  ToolResultTextContent,
  ToolResultEmbeddedResourceContent,
  ToolResultResourceContent,
  ToolResultContent,
  FileEdit,
  ToolResultFileEditContent,
  ToolResultTerminalContent,
  ToolResultSubagentContent,
  SessionActiveClient,
  PendingMessage,
  SessionInputAnswer,
  SessionInputAnswerValue,
  SessionInputTextAnswerValue,
  SessionInputNumberAnswerValue,
  SessionInputBooleanAnswerValue,
  SessionInputSelectedAnswerValue,
  SessionInputSelectedManyAnswerValue,
  SessionInputAnswered,
  SessionInputSkipped,
  SessionInputOption,
  SessionInputQuestion,
  SessionInputTextQuestion,
  SessionInputNumberQuestion,
  SessionInputBooleanQuestion,
  SessionInputSingleSelectQuestion,
  SessionInputMultiSelectQuestion,
  SessionInputRequest,
  UsageInfo,
  ErrorInfo,
  Snapshot,
  TerminalInfo,
  TerminalClientClaim,
  TerminalSessionClaim,
  TerminalClaim,
  TerminalState,
  TerminalContentPart,
  TerminalUnclassifiedPart,
  TerminalCommandPart,
} from './state.js';

export {
  PolicyState,
  SessionLifecycle,
  SessionStatus,
  TurnState,
  MessageAttachmentKind,
  ResponsePartKind,
  ToolCallStatus,
  ToolCallConfirmationReason,
  ToolCallCancellationReason,
  ConfirmationOptionKind,
  ToolResultContentType,
  PendingMessageKind,
  SessionInputAnswerState,
  SessionInputAnswerValueKind,
  SessionInputQuestionKind,
  SessionInputResponseKind,
  TerminalClaimKind,
} from './state.js';

// Action types
export type {
  ActionEnvelope,
  ActionOrigin,
  RootAgentsChangedAction,
  RootActiveSessionsChangedAction,
  SessionReadyAction,
  SessionCreationFailedAction,
  SessionTurnStartedAction,
  SessionDeltaAction,
  SessionResponsePartAction,
  SessionToolCallStartAction,
  SessionToolCallDeltaAction,
  SessionToolCallReadyAction,
  SessionToolCallApprovedAction,
  SessionToolCallDeniedAction,
  SessionToolCallConfirmedAction,
  SessionToolCallCompleteAction,
  SessionToolCallResultConfirmedAction,
  SessionToolCallContentChangedAction,
  SessionTurnCompleteAction,
  SessionTurnCancelledAction,
  SessionErrorAction,
  SessionTitleChangedAction,
  SessionUsageAction,
  SessionReasoningAction,
  SessionModelChangedAction,
  SessionServerToolsChangedAction,
  SessionActiveClientChangedAction,
  SessionActiveClientToolsChangedAction,
  SessionPendingMessageSetAction,
  SessionPendingMessageRemovedAction,
  SessionQueuedMessagesReorderedAction,
  SessionInputAnswerChangedAction,
  SessionInputCompletedAction,
  SessionInputRequestedAction,
  SessionTruncatedAction,
  SessionIsReadChangedAction,
  SessionIsArchivedChangedAction,
  SessionActivityChangedAction,
  SessionDiffsChangedAction,
  SessionConfigChangedAction,
  StateAction,
  RootTerminalsChangedAction,
  RootConfigChangedAction,
  TerminalDataAction,
  TerminalInputAction,
  TerminalResizedAction,
  TerminalClaimedAction,
  TerminalTitleChangedAction,
  TerminalCwdChangedAction,
  TerminalExitedAction,
  TerminalClearedAction,
  TerminalCommandExecutedAction,
  TerminalCommandFinishedAction,
  TerminalCommandDetectionAvailableAction,
} from './actions.js';

export { ActionType } from './actions.js';

// Generated action origin types
export type {
  RootAction,
  SessionAction,
  ClientSessionAction,
  ServerSessionAction,
  TerminalAction,
  ClientTerminalAction,
  ServerTerminalAction,
} from './action-origin.generated.js';

export { IS_CLIENT_DISPATCHABLE } from './action-origin.generated.js';

// Reducer functions
export {
  rootReducer,
  sessionReducer,
  terminalReducer,
  isClientDispatchable,
} from './reducers.js';

// Command types
export type {
  InitializeParams,
  InitializeResult,
  PingParams,
  ReconnectParams,
  ReconnectReplayResult,
  ReconnectSnapshotResult,
  ReconnectResult,
  SubscribeParams,
  SubscribeResult,
  CreateSessionParams,
  SessionForkSource,
  DisposeSessionParams,
  CreateTerminalParams,
  DisposeTerminalParams,
  ListSessionsParams,
  ListSessionsResult,
  ResourceReadParams,
  ResourceReadResult,
  ResourceWriteParams,
  ResourceWriteResult,
  ResourceListParams,
  DirectoryEntry,
  ResourceListResult,
  ResourceCopyParams,
  ResourceCopyResult,
  ResourceDeleteParams,
  ResourceDeleteResult,
  ResourceMoveParams,
  ResourceMoveResult,
  ResourceRequestParams,
  ResourceRequestResult,
  FetchTurnsParams,
  FetchTurnsResult,
  UnsubscribeParams,
  DispatchActionParams,
  AuthenticateParams,
  AuthenticateResult,
  ResolveSessionConfigParams,
  ResolveSessionConfigResult,
  ConfigPropertySchema,
  ConfigSchema,
  SessionConfigPropertySchema,
  SessionConfigSchema,
  SessionConfigCompletionsParams,
  SessionConfigCompletionsResult,
  SessionConfigValueItem,
  CompletionsParams,
  CompletionsResult,
  CompletionItem,
} from './commands.js';

export { ReconnectResultType, ContentEncoding, CompletionItemKind } from './commands.js';

// Notification types
export type {
  SessionAddedNotification,
  SessionRemovedNotification,
  SessionSummaryChangedNotification,
  AuthRequiredNotification,
  ProtocolNotification,
} from './notifications.js';

export { NotificationType, AuthRequiredReason } from './notifications.js';

// Message types (JSON-RPC wire format)
export type {
  JsonRpcRequest,
  JsonRpcSuccessResponse,
  JsonRpcErrorResponse,
  JsonRpcResponse,
  JsonRpcNotification,
  AhpErrorResponse,
  CommandMap,
  ServerCommandMap,
  NotificationMethodParams,
  ClientNotificationMap,
  ServerNotificationMap,
  NotificationMap,
  AhpRequest,
  AhpServerRequest,
  AhpSuccessResponse,
  AhpServerSuccessResponse,
  AhpResponse,
  AhpServerResponse,
  AhpNotification,
  AhpClientNotification,
  AhpServerNotification,
  ProtocolMessage,
} from './messages.js';

// Error codes
export {
  JsonRpcErrorCodes,
  AhpErrorCodes,
} from './errors.js';
export type {
  AhpErrorCode,
  JsonRpcErrorCode,
  AhpError,
  AhpErrorCodeWithData,
  AhpErrorDetailsMap,
  AuthRequiredErrorData,
  PermissionDeniedErrorData,
} from './errors.js';

// Version registry
export {
  PROTOCOL_VERSION,
  ACTION_INTRODUCED_IN,
  NOTIFICATION_INTRODUCED_IN,
  isActionKnownToVersion,
  isNotificationKnownToVersion,
  compareProtocolVersions,
} from './version/registry.js';
